[package]
name = "pahkat-rpc"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
tonic = "0.2.0"
bytes = "0.5.4"
prost = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds", "sync", "blocking"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
async-stream = "0.2.1"
http = "0.2"
tower = "0.3" 
parity-tokio-ipc = "0.7"
log = "0.4.8"
env_logger = "0.7.1"
crossbeam = "0.7.3"
pahkat_client = { path = "../pahkat-client-core", features = ["prefix"] }
cthulhu = { git = "https://github.com/cthulhu-rs/cthulhu" }
cursed = { git = "https://github.com/cthulhu-rs/cthulhu" }

[build-dependencies]
tonic-build = "0.2.0"
