[package]
name = "pahkat-rpc"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
tonic = { git = "https://github.com/bbqsrc/tonic", branch = "feature/uds", features = ["prost"] }
bytes = "0.5.4"
prost = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds", "sync", "blocking", "signal"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
async-stream = "0.2.1"
http = "0.2"
tower = "0.3" 
parity-tokio-ipc = "0.7"
log = "0.4.8"
env_logger = "0.7.1"
crossbeam = "0.7.3"
pahkat-client = { path = "../pahkat-client-core", default-features = false }
cthulhu = { git = "https://github.com/cthulhu-rs/cthulhu" }
cursed = { git = "https://github.com/cthulhu-rs/cthulhu" }
anyhow = "1.0.28"
stream-cancel = "0.5.2"

[build-dependencies]
tonic-build = "0.2.0"

[features]
windows = ["pahkat-client/windows"]
prefix = ["pahkat-client/prefix"]
macos = ["pahkat-client/macos"]
