[package]
name = "pahkat-rpc"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
tonic = "0.1.1"
bytes = "0.5.4"
prost = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
async-stream = "0.2"
http = "0.2"
tower = "0.3" 
parity-tokio-ipc = "0.7"

[build-dependencies]
tonic-build = "0.1.1"