[package]
name = "pahkat-rpc"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]


[dependencies]
pahkat-client = { path = "../pahkat-client-core" }
tonic = { git = "https://github.com/bbqsrc/tonic", branch = "master", features = ["prost"] }
bytes = "0.5.4"
prost = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "rt-util", "time", "stream", "fs", "macros", "uds", "sync", "blocking", "signal"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
async-stream = "0.2.1"
http = "0.2"
tower = "0.3" 
parity-tokio-ipc = { git = "https://github.com/bbqsrc/parity-tokio-ipc" }
log = "0.4.8"
env_logger = "0.7.1"
crossbeam = "0.7.3"
cthulhu = { git = "https://github.com/cthulhu-rs/cthulhu", branch = "feature/bytes-plus-len" }
cursed = { git = "https://github.com/cthulhu-rs/cthulhu", branch = "feature/bytes-plus-len" }
anyhow = "1.0.28"
stream-cancel = "0.5.2"
once_cell = "1.3.1"
fern = "0.6.0"
structopt = "0.3.14"
serde_json = "1.0.51"
serde = "1.0.106"
url = "2.1.1"
windows-service = { git = "https://github.com/mullvad/windows-service-rs" }
winlog = "0.2.6"
flexi_logger = "0.15.2"
chrono = "0.4.11"

[build-dependencies]
tonic-build = "0.2.0"

[features]
# default = ["server"]
# server = []
# client = []
windows = ["pahkat-client/windows"]
prefix = ["pahkat-client/prefix"]
macos = ["pahkat-client/macos"]
